### ISSUE TITLE
下载程序后，运行报报错

### ISSUE THREAD

**Issue by xiongliang120** [tomming233/blog#1]
'utf8' codec can't decode byte 0xca in position 3: invalid continuation byte. You passed in 'E:\\\xca\xe9\xbc\xae\\python\\Django\\Django \xcf\xee\xc4\xbf\\11\\blog-f91fa845daf6d5beba19a0c5982bbe49321b5cd7\\blog\\templates' (<type 'str'>)

**Comment by tomming233** [comment]
请先确保环境为python3.5。若可以，请报错回溯全部贴出来
