### ISSUE TITLE
怎么没有数据库还有登陆校验

### ISSUE THREAD

**Issue by livan123** [tomming233/blog#15]
大神，登陆校验写在哪里了？为什么我把数据库中的用户名和密码做了修改依然不能登陆？

**Comment by wmingj** [comment]
报错信息贴一下

**Comment by livan123** [comment]
报错我整理一下发出来，想咨询一下初始登录的密码和账号是多少？我刚开始接触Django，还没有玩熟，一直没进去

**Comment by livan123** [comment]
Please enter the correct username and password for a staff account. Note that both fields may be case-sensitive.
没有找到账号校验的地方在哪里~~

**Comment by wmingj** [comment]
帐号密码在settings.py中填写

**Comment by livan123** [comment]
不好意思，能不能具体一点，setting中没有找到

**Comment by livan123** [comment]
搞定了，哈哈，谢谢

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video
